### ISSUE TITLE
Consider Removing Limit From Query Interface

### ISSUE THREAD

**Issue by jrduncans** [d2a4u/meteor#230]
Limit is an optional parameter to the Query API: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-Limit

When not sent, AWS automatically limits the data to around 1MB. Being forced to pick a value to exceed that amount adds friction to using the API. Since Meteor automatically pages through using `lastEvaluatedKey`, setting a limit doesn't seem to be of value, as it doesn't limit how many records Meteor returns, just the size of a batch.

**Comment by d2a4u** [comment]
That sounds good to me. It would be amazing if you can raise a PR to remove `limit` parameter

**Comment by jrduncans** [comment]
Ok, I've got two branches, let me know which one you'd prefer as the PR:

- [Removes limit parameter](https://github.com/jrduncans/meteor/tree/limit-removal)
- [Adds methods without limit parameter and deprecates methods with limit parameter](https://github.com/jrduncans/meteor/tree/deprecate-limit)

**Comment by d2a4u** [comment]
Hi, sorry for late reply. My laptop is dead and getting a new one is quite difficult atm. [Deprecation branch](https://github.com/d2a4u/meteor/compare/main...jrduncans:deprecate-limit) looks good to me. Thanks

**Comment by jrduncans** [comment]
Closed in #240
